import "./globals.css";
import Navigation from "@/components/Navigation"
import Footer from "@/components/Footer"
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      className="h-full"
    >
      <body className="min-h-full flex flex-col">
<Navigation/>
        
        {children}</body>
        <Footer/>
    </html>
  );
}
