import "./globals.css";
import Link from "next/link";


export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
    >
      <body className="min-h-full flex flex-col">
<header style={{ padding: "1rem", borderBottom: "1px solid #ccc" }}>
          <nav>
            <ul style={{ display: "flex", gap: "1rem", listStyle: "none" }}>
              <li><Link href="/">Home</Link></li>
              <li><Link href="/about">About</Link></li>
              <li><Link href="/about/team">Our Team</Link></li>
            </ul>
          </nav>
        </header>
        
        {children}</body>
    </html>
  );
}
